services:
  gpt-sovits:
    build: .
    image: gpt-sovits:latest   # please change the image name and tag base your environment. If the tag contains the word 'elite', such as "latest-elite", it indicates that the image does not include the necessary models such as GPT-SoVITS, UVR5, Damo ASR, etc. You will need to download them yourself and map them into the container.
    container_name: gpt-sovits-stage-container
    environment:
      - is_half=False
      - is_share=False
      - LC_ALL=zh_CN.UTF-8
      - LANG=zh_CN.UTF-8
    volumes:
      - /home/docker/mnt/TeamSpace/TTD-Space/output:/workspace/output
      - /home/docker/mnt/TeamSpace/TTD-Space/logs:/workspace/logs
      - /home/docker/mnt/TeamSpace/TTD-Space/SoVITS_weights:/workspace/SoVITS_weights
      - /home/docker/mnt/TeamSpace/TTD-Space/GPT_weights:/workspace/GPT_weights
      - /home/docker/mnt/TeamSpace/TTD-Space/reference:/workspace/reference
      - /home/docker/mnt/TeamSpace:/workspace/TeamSpace
      - /home/docker/GPT-SoVITS/webui.py:/workspace/webui.py
    working_dir: /workspace
    ports:
      - "9580:9880"
      - "9571:9871"
      - "9572:9872"
      - "9573:9873"
      - "9574:9874"
    shm_size: 32G
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
