services:
  base:
    build: .
    image: gpt-sovits:v2   # please change the image name and tag base your environment. If the tag contains the word 'elite', such as "latest-elite", it indicates that the image does not include the necessary models such as GPT-SoVITS, UVR5, Damo ASR, etc. You will need to download them yourself and map them into the container.
    environment:
      - is_half=False
      - is_share=False
      - LC_ALL=zh_CN.UTF-8
      - LANG=zh_CN.UTF-8
    volumes:
      - /home/docker/mnt/TeamSpace/TTD-Space/GPT_Sovits_v2/output:/workspace/output
      - /home/docker/mnt/TeamSpace/TTD-Space/GPT_Sovits_v2/logs:/workspace/logs
      - /home/docker/mnt/TeamSpace/TTD-Space/GPT_Sovits_v2/SoVITS_weights:/workspace/SoVITS_weights_v2
      - /home/docker/mnt/TeamSpace/TTD-Space/GPT_Sovits_v2/GPT_weights:/workspace/GPT_weights_v2
      - /home/docker/mnt/TeamSpace/TTD-Space/GPT_Sovits_v2/reference:/workspace/reference
      - /home/docker/mnt/TeamSpace:/workspace/TeamSpace
    working_dir: /workspace
    shm_size: 32G
    stdin_open: true
    tty: true
    restart: unless-stopped
  sovits-training-3070:
    container_name: '3070'
    profiles:
      - production
    extends: base
    ports:
      - "9880:9880"
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["2"] #9874用3070，根据nvidia-smi做好映射
            capabilities: [gpu]
  sovits-training-3080:
    container_name: '3080'
    profiles:
      - production
    extends: base
    ports:
      - "9980:9880"
      - "9971:9871"
      - "9972:9872"
      - "9973:9873"
      - "9974:9874"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["1"]
            capabilities: [gpu]
  sovits-inference-p5000:
    container_name: 'p5000'  
    profiles:
      - production
    extends: base
    ports:
      - "9180:9880"
      - "9171:9871"
      - "9172:9872"
      - "9173:9873"
      - "9174:9874"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]
  sovits-inference-cpu:
    container_name: 'cpu'
    profiles:
      - production
    extends: base
    ports:
      - "9280:9880"
      - "9271:9871"
      - "9272:9872"
      - "9273:9873"
      - "9274:9874"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ["0"]
    #         capabilities: [gpu]